### ISSUE TITLE
Unable to find referenced entities

### ISSUE THREAD

**Issue by danb5** [lukas-hetzenecker/home-assistant-remote#46] opened 2020-06-17 13:09 UTC
Everything works fine but in the master HAss I get the following error in my log constantly:
Unable to find referenced entities switch.table_lamp

I get this for each switch I have exposed from the remote HAss

**Comment by gislis2** [comment] 2020-07-25 20:12
Similar issue here. 

Master: Docker HA 
Slave: RBP 3B directly running HA on SD

Set up absolute bare minimum RBP to squeeze SD card life. Use it only for Ikea Tradfri and Philips Hue due to Docker UDP issues. Everything works perfectly except the massive amount of WARNING logs 
Seems to happen during every time the Master makes changes to the lights

- Directly changing a light

- scene

- automation
Doesn't seem to log it when lights are changed externally. Tried:
- Ikea/Hue app on phone
- Tradfri motion sensor activating a tradfri light in entryroom
- Slave HA state changes
- "manual override" by flicking wallswitch off for 2 sec, then on


`2020-07-25 20:00:35 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.rbp_tv_bar`

**Comment by Shogun1978** [comment] 2020-09-27 12:57
Also running into this issue, using remote the pyloxone integration. In one setup, it works great (0.114.4) and on another (testing) system with 0.115.x I get the "unable to find referenced entities" error (light, switch... simply doesn't work)

**Comment by mg0716** [comment] 2020-11-27 14:21
Having the same issue here. Here's what I'm seeing:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:464 
First occurred: November 26, 2020, 11:07:41 AM (2149 occurrences) 
Last logged: 9:17:59 AM

Unable to find referenced entities light.office_ceiling_light_1, light.office_ceiling_light_2
Unable to find referenced entities light.office_hue_play_1, light.office_hue_play_2, light.office_hue_play_3
Unable to find referenced entities light.office_hue_play_1
Unable to find referenced entities light.office_hue_play_2
Unable to find referenced entities light.office_hue_play_3
```

This is the error on my main HA, where the devices reside on my remote HA. Though the lights do seem to operate as expected, so I'm not entirely sure what's going on here. Any insight?

**Comment by postlund** [comment] 2020-12-21 22:19
Duplicate of #39.

**Closed by postlund** 2020-12-21 22:19 UTC
