### ISSUE TITLE
Connected but sensors don't update

### ISSUE THREAD

**Issue by lancelon** [lukas-hetzenecker/home-assistant-remote#61] opened 2020-11-13 11:54 UTC
I'm connected to my remote instance, the binary sensor shows connected, but my sensors aren't updating. Is there any other way, besides the sensor, I can see why things aren't working? The remote assistant pointing the OTHER direction is working a treat, sensors ARE updating.
Is it perhaps not possible to have two remote assistants working bidirectionally?
Cheers

**Comment by herrlado** [comment] 2020-11-14 18:02
I have the same issue. I have opened an issue yesterday and the have closed it again, as thought it were working then. But today, last update was 8 hours ago. In the enabled log I see
```020-11-14 12:36:33 DEBUG (MainThread) [custom_components.remote_homeassistant] received: {'id': 1, 'type': 'event', 'even```
And Iti nos 19:00 O'clock. The sensors are showing different values on the remote haass. I do not know where to look for the solution.

**Comment by lancelon** [comment] 2020-11-19 18:38
I downgraded to 2.1, that seemed to help...but only briefly. Now not working again.  I'm about ready to give up and go back to passing messages via MQTT.

**Comment by war1000** [comment] 2020-11-30 17:16
I am having this same issue. Is there anyway to force this?

**Comment by lancelon** [comment] 2020-11-30 17:18
Sadly I’ve seen no sign there’s any interest in fixing this massive bug

**Comment by war1000** [comment] 2020-11-30 17:33
Is there any workarounds? I don't want to go back to mqtt as I am not sure how to report battery levels with that method.

**Comment by postlund** [comment] 2020-11-30 17:41
I have not seen this issue myself, but it fixing it seems rather urgent and important. One thing that is not implemented is heartbeats (ping-ping), which at least would detect if the connection isn't working. It's to tell if it will "fix" the root cause, but perhaps it can help (by exercising the connection a bit). I can try to implement it later tonight, if I have some time.

For reference: https://developers.home-assistant.io/docs/api/websocket/#pings-and-pongs

**Comment by war1000** [comment] 2020-11-30 17:50
thank you very much and very kind of you!

**Comment by abattech** [comment] 2020-11-30 19:05
Same issue is happening in my setup. Upon restart of HA, the states of my remote device trackers are acquired properly, but they do not seem to be updated after that...

**Comment by postlund** [comment] 2020-11-30 21:46
I have created a PR, #73, that adds support for the mentioned heartbeats. Hopefully this will detect if the connection doesn't work and re-connect. Please try it out and let me know if it works.

**Comment by war1000** [comment] 2020-12-01 02:38
> I have created a PR, #73, that adds support for the mentioned heartbeats. Hopefully this will detect if the connection doesn't work and re-connect. Please try it out and let me know if it works.

I have not downloaded a branch before so just want to make sure....I just copy the file in #73 and override the one I have in custom component, right?

**Comment by war1000** [comment] 2020-12-01 03:19
nvm...brother showed me how to download the postlund:heartbeat repo. I just copied over the __init__.py file and overwrote the existing with you and restarted HA. I will report back on disconnect tomorrow. Thanks!

**Comment by war1000** [comment] 2020-12-01 03:23
actually nevermind. uploaded/overwrote the full remote_homeassistant folder and restarted. no error so far.

**Comment by war1000** [comment] 2020-12-02 21:12
> I have created a PR, #73, that adds support for the mentioned heartbeats. Hopefully this will detect if the connection doesn't work and re-connect. Please try it out and let me know if it works.

So this morning I tested it and seems like it did lose connection still.

Main instance ![image](https://user-images.githubusercontent.com/57807544/100931871-1ae8f180-34b9-11eb-898a-f83d35563cd0.png)

Remote instance where the sensor is connected 
![image](https://user-images.githubusercontent.com/57807544/100931985-38b65680-34b9-11eb-9b5b-99fbaea6380c.png)

**Comment by abattech** [comment] 2020-12-02 21:24
PR #73 seems to work for me. The connection was lost at some point (judging from "heartbeat failed" log message), but my remote device trackers do get updates, so I assume the reconnection worked fine. Thanks for the fix!

**Comment by war1000** [comment] 2020-12-02 21:45
> PR #73 seems to work for me. The connection was lost at some point (judging from "heartbeat failed" log message), but my remote device trackers do get updates, so I assume the reconnection worked fine. Thanks for the fix!

I will continue the testing. I have the remote instance on a 6 hour restart schedule. I am not sure if that is messing up my testing. Will report back in 2 days. Thanks!

**Comment by matata86** [comment] 2020-12-03 18:40
PR 73 not working for me. Still same problem. 😒

**Comment by Highvolt** [comment] 2020-12-16 21:34
I was having the same issue after configuring using the UI. I solved my problem by subscribing the following events in the last step of the configuration:

- state_changed
- service_registered

**Comment by war1000** [comment] 2020-12-16 21:39
> I was having the same issue after configuring using the UI. I solved my problem by subscribing the following events in the last step of the configuration:
> 
> * state_changed
> * service_registered

Brother, can you please elaborate for us mortals? :D This so far is working for me but if the remote instance is rebooted, the master instance shows that sensors as missing.

**Comment by postlund** [comment] 2020-12-16 21:43
Mhmm, this might be my doing... In the YAML schema, those events are used as default value unless something is specified. That's not how it works when setting up from config flow (no events are subscribed to). So that becomes a problem.

@lukas-hetzenecker Based on the above, do you see any reason not to hardcode those events in as "default" (regardless of what's in the config) and just let the config just append to those?

**Comment by Highvolt** [comment] 2020-12-17 16:34
> > I was having the same issue after configuring using the UI. I solved my problem by subscribing the following events in the last step of the configuration:
> > 
> > * state_changed
> > * service_registered
> 
> Brother, can you please elaborate for us mortals? :D This so far is working for me but if the remote instance is rebooted, the master instance shows that sensors as missing.

Sure.
You go to Integrations configuration:
![2020-12-17_16-31](https://user-images.githubusercontent.com/182139/102515421-a9e33580-4085-11eb-8fed-d32ff2995cf2.png)

And in the last step you add all the events:
![2020-12-17_16-32](https://user-images.githubusercontent.com/182139/102515449-b49dca80-4085-11eb-8aa3-8f8afd33da5a.png)

**Comment by postlund** [comment] 2020-12-23 13:16
These events are now subscribed to internally by the component, so no need to specify at all. Currently only on master, will hopefully make a release soon.

**Closed by postlund** 2020-12-23 13:16 UTC
