### ISSUE TITLE
Error when starting homekit

### ISSUE THREAD

**Issue by mattlongman** [lukas-hetzenecker/home-assistant-remote#23] opened 2019-10-30 20:00 UTC
Firstly, this component seems like a true miracle after messing around with socat, ser2net and usbip for what seems like forever, so, thank you!

I'm having an issue with with it when I start the homekit component. I have homekit disabled on startup, but when I run homekit.start, I immediately see the following in the log:

`019-10-30 18:36:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 264, in _recv
    callback(message)
  File "/config/custom_components/remote_homeassistant/__init__.py", line 387, in fire_event
    self._entities.remove(entity_id)
KeyError: 'persistent_notification.config_entry_discovery'`

After that, I might be able to switch one or two devices on or off (status might update in master hassio or homekit, mainly doesn't) before the devices on the remote instance stop being controllable from the master (locally and through homekit control).

I'm using the current version. I've tried changing the default port, but get the same result. Also tried removing all subscribe events, same result.

I'm seeing this behaviour in homeassistant version 0.100.3 & 0.101.0.

My config:

```
remote_homeassistant:
  instances:
  - host: !secret usb_ip
    port: 8234
    access_token: !secret usb
    entity_prefix: "usb_"
    include:
      domains:
      - sensor
      - switch
      - group
      - light
      - climate
    subscribe_events:
    - state_changed
    - service_registered
    - zwave.network_ready
    - zwave.node_event
```
Is there anything I'm missing?

**Comment by mattlongman** [comment] 2019-11-01 20:36
Same issue in 0.101.1. I've tried to debug this some more, but not made any progress.

Bit of a clarification on the issue though: after doing a bit more testing, the control seems to remain for longer than I thought (perhaps doesn't drop at all - need to test further), but the master instance doesn't get any status updates for entities.

E.g. turn Office Light on through master instance, light comes on, but master instance UI doesn't update to reflect that (toggle in UI pings back to off). Click Office Light toggle back on, and before it pings back, click it off again, and the light will turn off.

So it's sending the right commands, just not reflecting that in home assistant (or homekit, for that matter).

**Comment by mattlongman** [comment] 2019-11-02 00:10
I still can't work out what in the homekit component is conflicting with this or why it's erroring, so I resorted to doing the obvious thing and suppressed the KeyError on line 387. Seems to work now! Will test further tomorrow.

**Comment by lukas-hetzenecker** [comment] 2019-11-02 00:36
Oh! I think I've found the problem.
You're using a `entity_prefix`. 
In the line where `self._entities.remove(entity_id)`, the prefix is not added beforehand.
I will try to come up with a bugfix tomorrow.

**Comment by lukas-hetzenecker** [comment] 2019-11-02 00:40
Yep, could reproduce the error

**Comment by lukas-hetzenecker** [comment] 2019-11-02 00:51
Should be fixed in master now

**Closed** 2019-11-02 00:50 UTC

**Comment by mattlongman** [comment] 2019-11-02 00:58
Thanks Lukas. I'll check this in the morning.

**Comment by mattlongman** [comment] 2019-11-02 10:29
Yep, all good now. Thanks

**Comment by lukas-hetzenecker** [comment] 2019-11-02 11:03
```
File "/config/custom_components/remote_homeassistant/__init__.py", line 393, in fire_event
```

still looks like the old version. Made a new release new, you can update via HACS

**Comment by mattlongman** [comment] 2019-11-02 11:07
> ```
> File "/config/custom_components/remote_homeassistant/__init__.py", line 393, in fire_event
> ```
> 
> still looks like the old version. Made a new release now, you can update via HACS

That error was after deleting the folder and downloading the zip from GitHub directly. Error is now on a different line, so is definitely newer than the previous.
